### ISSUE TITLE
Scrolling can scroll to invisible hotbars

### ISSUE THREAD

**Issue by trienow** [rolandoislas/multi-hotbar#45]
This might have something to do with #39, but I was not sure.

# Versions
Minecraft Version: 1.12.2
Forge Version: 14.23.0.2517
Multi-Hotbar Version: 1.12.2-3.1-build-T85

# What Happend
When I scroll out of the beginning of the first or the end of the of the second hotbar (I only have two), the item slot selector moves into an invisible hotbar.
I am able to place blocks and use items from the invisible hotbar.

# Screenshot
![The item selector, not being on my hotbar](https://user-images.githubusercontent.com/8478950/33241043-a1b7f066-d2c0-11e7-85cd-d2bc5d121316.png)

![The invisible hotbar enabling me to place stone](https://user-images.githubusercontent.com/8478950/33241156-fc14e586-d2c1-11e7-8c54-a15bb7ca8e28.png)

**Comment by rolandoislas** [comment]
Fixed in v3.2.

**Comment by trienow** [comment]
Unfortunately it did not fix the problem.
I linked a video of the problem here: http://cdn.trienow.de/hotbar.mp4
Just to clarify: I do not press any Buttons while slowly scrolling down on my mouse.

# Versions
Minecraft Version: 1.12.2
Forge Version: 14.23.1.2555
Multi-Hotbar Version: 1.12.2-3.2-build-t113

**Comment by rolandoislas** [comment]
This appears to be an issue with the core mod installed in conjunction with version 3.2. The core mod is only required in version 4.0 and higher.

**Comment by trienow** [comment]
Oh, I'm sorry. I forgot. You did write that on the curse page. Thanks for the help :)
